### ISSUE TITLE
Error: "Cannot find appropriate message handler for comm_info_request"

### ISSUE THREAD

**Issue by shuangwu** [alexbw/bayarea-dl-summerschool#1]
I have followed the instructions in README.md on OS X, but when I run the notebook, I ran into following issue:

```
 ~/anaconda/bin/jupyter notebook
[I 12:10:14.129 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 12:10:14.695 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 12:10:14.695 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 12:10:14.700 NotebookApp] [nb_conda] enabled
[I 12:10:14.767 NotebookApp] [nb_anacondacloud] enabled
[I 12:10:14.777 NotebookApp] Serving notebooks from local directory: /Users/shuang/github/bayarea-dl-summerschool/notebooks
[I 12:10:14.777 NotebookApp] 0 active kernels
[I 12:10:14.777 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 12:10:14.777 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 12:10:34.747 NotebookApp] Kernel started: a441bb05-49be-4642-b6c3-f5aaa580205d
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU

[I 12:10:35.187 NotebookApp] Adapting to protocol v4.0 for kernel a441bb05-49be-4642-b6c3-f5aaa580205d
lua: /Users/shuang/anaconda/share/lua/5.2/itorch/main.lua:350: Cannot find appropriate message handler for comm_info_request
stack traceback:
        [C]: in function 'assert'
        /Users/shuang/anaconda/share/lua/5.2/itorch/main.lua:350: in function </Users/shuang/anaconda/share/lua/5.2/itorch/main.lua:348>
        (...tail calls...)
        /Users/shuang/anaconda/share/lua/5.2/lzmq/poller.lua:75: in function 'poll'
        /Users/shuang/anaconda/share/lua/5.2/lzmq/impl/loop.lua:307: in function 'poll'
        /Users/shuang/anaconda/share/lua/5.2/lzmq/impl/loop.lua:325: in function 'sleep_ex'
        /Users/shuang/anaconda/share/lua/5.2/lzmq/impl/loop.lua:370: in function 'start'
        /Users/shuang/anaconda/share/lua/5.2/itorch/main.lua:381: in main chunk
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: in ?
[I 12:12:06.514 NotebookApp] Kernel shutdown: a441bb05-49be-4642-b6c3-f5aaa580205d
```

**Comment by alexbw** [comment]
Hey, will look into this soon.

**Comment by alexbw** [comment]
Thanks for the bug report. This is an issue upstream in facebook's iTorch. They've fixed it in later commits, and I' merging them in.

**Comment by alexbw** [comment]
Rebuilding the conda repo for iTorch, should be up soon.

**Comment by alexbw** [comment]
Ok if you update your `lua-itorch` package in conda, it should work.
Try
`conda update lua-itorch -y -c alexbw`
or, if that's finicky, do a fresh install of `anaconda` and `lua-science`

**Comment by skeydan** [comment]
Hi, I have the same problem, after trying all the above steps and using lua 5.2 as well as lua 5.3.

My original installation steps were:
conda create --name lua53 --clone p35
source activate lua53
conda install lua=5.3 lua-itorch -y -c alexbw
jupyter notebook

and the error is

[I 10:29:33.414 NotebookApp] Adapting to protocol v4.0 for kernel 4b134848-a6ae-45fe-9d33-70c17edd52a3
lua: ...ython/anaconda2/envs/lua53/share/lua/5.3/itorch/main.lua:350: Cannot find appropriate message handler for comm_info_request
stack traceback:
	[C]: in function 'assert'
	...ython/anaconda2/envs/lua53/share/lua/5.3/itorch/main.lua:350: in function <...ython/anaconda2/envs/lua53/share/lua/5.3/itorch/main.lua:348>
	(...tail calls...)
	...ython/anaconda2/envs/lua53/share/lua/5.3/lzmq/poller.lua:75: in method 'poll'
	...on/anaconda2/envs/lua53/share/lua/5.3/lzmq/impl/loop.lua:307: in method 'poll'
	...on/anaconda2/envs/lua53/share/lua/5.3/lzmq/impl/loop.lua:325: in method 'sleep_ex'
	...on/anaconda2/envs/lua53/share/lua/5.3/lzmq/impl/loop.lua:370: in method 'start'
	...ython/anaconda2/envs/lua53/share/lua/5.3/itorch/main.lua:381: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: in ?

It would be great if you could have a look, as I see from the above that the upstream error should have been merged in for a long time?
Many thanks in advance!!!

**Comment by alexbw** [comment]
Try installing using Python 2.7. All of the packages were built against Python 2.7, and I haven't tested against Python 3.x

**Comment by skeydan** [comment]
Hi, thanks for the quick answer! Gonna try when I'm back from vacation :-)
Happy holidays!
